DROP TABLE IF EXISTS MEMSOURCE_CREDENTIALS;

CREATE TABLE MEMSOURCE_CREDENTIALS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  token VARCHAR(250) NOT NULL
);
